adapter:
  adapter_name: dingding

dingding:
  app_secret: "xxxxxx"
  access_token: "xxxxxx"

wechat:
  app_secret: "xxxxx"

zabbix:
  url: "http://xxxxxx/api_jsonrpc.php"
  username: "xxxx"
  password: "xxxx"