adapter:
  adapter_name: dingding

dingding:
  app_secret: "xxx-K5WcNgZaR3Pq2"
  access_token: "xxxx"

wechat:
  app_secret: "xxxxx"

zabbix:
  url: "http://4xxx:8088/api_jsonrpc.php"
  username: "Admin"
  password: "zabbix"

jenkins:
  url: "http://xxxx"
  username: "admin"
  password: "admin"

ssh:
  file_path: "../chatops/config/hosts/hosts"

redis:
  ipaddr: "xxx.xxx.xxx.172:6379"