adapter:
  adapter_name: dingding

dingding:
  app_secret: "xxx-xxx"
  access_token: "xxx"

wechat:
  app_secret: "xxxxx"

zabbix:
  url: "http://xxxx/api_jsonrpc.php"
  username: "xxx"
  password: "xxx"

jenkins:
  url: "http://xxx"
  username: "xx"
  password: "xx"